<a href="https://colab.research.google.com/github/harikrishna0007/Hari_Data690/blob/main/Assignment05/part_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

Numpy Arrays

In [2]:
a= np.array([1, 2, 3, 4])

In [3]:
b = np.array([0, .5, 1, 1.5, 2])

In [4]:
a[0], a[1]

(1, 2)

In [5]:
a[1:3]

array([2, 3])

In [6]:
a[1:-1]

array([2, 3])

array types

In [7]:
a.dtype

dtype('int64')

In [8]:
b.dtype

dtype('float64')

In [9]:
np.array([1, 2, 3, 4], dtype=np.float) # convert to float

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [10]:
np.array([1, 2, 3, 4], dtype=np.int8) # Convert to int

array([1, 2, 3, 4], dtype=int8)

In [11]:
d = np.array([{'a':1}, sys])

In [12]:
d.dtype

dtype('O')

Dimension and shape

In [13]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [14]:
A.shape

(2, 3)

In [15]:
A.ndim # number of dimensions (axes) of the ndarray

2

In [16]:
A.size

6

In [17]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [18]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [19]:
B.shape

(2, 2, 3)

In [20]:
B.size

12

In [21]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [22]:
C.dtype

dtype('O')

In [23]:
C.shape

(2,)

In [24]:
C.size

2

In [25]:
C.ndim

1

In [26]:
type(C[0])

list

Indexing and Slicing of Matrices

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [28]:
A[1]

array([4, 5, 6])

In [29]:
A[1][0]

4

In [30]:
A[1] = np.array([10, 10, 10])

In [31]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [32]:
A[1]

array([10, 10, 10])

In [33]:
A[1][0]

10

In [34]:
A[1, 0]

10

In [35]:
A[0:2]

array([[ 1,  2,  3],
       [10, 10, 10]])

In [36]:
A[:, :2]

array([[ 1,  2],
       [10, 10],
       [ 7,  8]])

In [37]:
A[:2, :2]

array([[ 1,  2],
       [10, 10]])

In [38]:
A[:2, 2:]

array([[ 3],
       [10]])

In [39]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [40]:
A[2] = 99

In [41]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary statistics


In [42]:
a = np.array([1, 2, 3, 4])

In [43]:
a.sum()

10

In [44]:
a.min()

1

In [45]:
a.max()

4

In [46]:
a.std()

1.118033988749895

In [47]:
a.var()

1.25

In [48]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [49]:
A.sum()

45

In [50]:
A.mean()

5.0

In [51]:
A.std()

2.581988897471611

In [52]:
A.sum(axis=0)

array([12, 15, 18])

In [53]:
A.sum(axis=1)

array([ 6, 15, 24])

In [54]:
A.mean(axis=0)

array([4., 5., 6.])

In [55]:
A.mean(axis=1)

array([2., 5., 8.])

In [56]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [57]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized operations

In [58]:
a = np.arange(4)

In [59]:
a

array([0, 1, 2, 3])

In [60]:
a+2

array([2, 3, 4, 5])

In [61]:
a*2

array([0, 2, 4, 6])

In [62]:
a

array([0, 1, 2, 3])

In [63]:
a+=100

In [64]:
a

array([100, 101, 102, 103])

In [65]:
l = [0, 1, 2, 3]

In [66]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [67]:
a = np.arange(4)

In [68]:
a

array([0, 1, 2, 3])

In [69]:
b = np.array([10, 10, 10, 10])

In [70]:
b

array([10, 10, 10, 10])

In [71]:
a+b

array([10, 11, 12, 13])

Boolean arrays

In [72]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [73]:
a[0], a[-1]

(0, 3)

In [74]:
a[[0, -1]]

array([0, 3])

In [75]:
a[[True, False, False, True]]

array([0, 3])

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a >= 2

array([False, False,  True,  True])

In [78]:
a[a >= 2]

array([2, 3])

In [79]:
a[a > a.mean()]

array([2, 3])

In [80]:
a[~(a > a.mean())]

array([0, 1])

In [81]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [82]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [83]:
A = np.random.randint(100, size=(3, 3))
A

array([[66, 78,  2],
       [10, 99, 63],
       [89, 11, 13]])

In [84]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([66,  2, 99, 89, 13])

In [85]:
A > 30

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False, False]])

In [86]:
A[A > 30]

array([66, 78, 99, 63, 89])

Linear Algebra

In [87]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [88]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [89]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [90]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [91]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [92]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory

In [94]:
sys.getsizeof(1)

28

In [95]:
sys.getsizeof(10**100)

72

In [96]:
np.dtype(int).itemsize

8

In [97]:
np.dtype(np.int8).itemsize

1

In [98]:
np.dtype(float).itemsize


8

For larger lists

In [99]:
sys.getsizeof([1])

80

In [100]:
np.array([1]).nbytes

8

In [101]:
l = list(range(100000))

In [102]:
a = np.arange(100000)

In [103]:
%time np.sum(a ** 2)

CPU times: user 905 µs, sys: 132 µs, total: 1.04 ms
Wall time: 3.23 ms


333328333350000

In [104]:
%time sum([x ** 2 for x in l])

CPU times: user 44.5 ms, sys: 5.07 ms, total: 49.6 ms
Wall time: 54.6 ms


333328333350000

Usefull Numpy Functions

1. random

In [105]:
np.random.random(size=2)

array([0.01647746, 0.93368887])

In [106]:
np.random.normal(size=2)

array([-1.08500044,  0.92025575])

In [107]:
np.random.rand(2, 4)

array([[0.59655219, 0.95109639, 0.09776339, 0.66143886],
       [0.87282964, 0.62146229, 0.75496372, 0.04303562]])

2. arange

In [108]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [110]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

3. reshape

In [111]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [112]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

4. linspace

In [113]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [114]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [115]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

5. zeros, ones, empty

In [116]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [117]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [118]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [119]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [120]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
  np.empty(5)

array([1., 1., 1., 1., 1.])

In [122]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [123]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [126]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [127]:
"Hello World"[6]

'W'